"""add paper summary

Revision ID: 2393745f17a8
Revises: 8c686b972a9f
Create Date: 2026-07-16 23:22:25.437242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2393745f17a8'
down_revision: Union[str, Sequence[str], None] = '8c686b972a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('summary', sa.Text(), nullable=True))
    op.alter_column('papers', 'sha256_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'sha256_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('papers', 'summary')
    # ### end Alembic commands ###
