"""add sha256 hash to papers

Revision ID: 8c686b972a9f
Revises: 91798c049fa4
Create Date: 2026-07-12 16:48:26.690782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c686b972a9f'
down_revision: Union[str, Sequence[str], None] = '91798c049fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'sha256_hash')
    # ### end Alembic commands ###
