"""add extracted text fields

Revision ID: 91798c049fa4
Revises: 5ef2dfa66238
Create Date: 2026-07-10 17:11:36.687920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91798c049fa4'
down_revision: Union[str, Sequence[str], None] = '5ef2dfa66238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('word_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'word_count')
    op.drop_column('papers', 'page_count')
    op.drop_column('papers', 'raw_text')
    # ### end Alembic commands ###
